runtime: python39

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  FLASK_ENV: 'development'  # Đặt biến môi trường FLASK_ENV thành 'development' cho môi trường phát triển

